[package]
name = "hacking_trading_app"
version = "0.1.0"
authors = ["Jinliang Shi <jinliangshi@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
